name: Hello World Training Workflow

on:
 workflow_dispatch:  # Для ручного запуска
  issues:             # Для запуска при событиях с Issue
    types: [opened, edited]  # Только при создании или редактировании Issue
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User
        run: echo "Hello World!"
jobs:
  greet:
    env:
      MY_ENV: "John Doe"  # Переменная окружения
    runs-on: ubuntu-latest
    steps:
      - name: Run a multi-line script
        run: |
          echo "Hello $MY_ENV"
          echo "Hello $GITHUB_ACTOR"
